Mesd\RuleBundle\Entity\ActionCallEntity:
    type: entity
    table: mesd_rule_action_call
    repositoryClass: Mesd\RuleBundle\Repository\ActionCallRepository
    fields:
        id:
            column: id
            type: bigint
            id: true
            generator:
                strategy: AUTO
        raw_input_value:
            column: raw_input_value
            type: text
            nullable: false
    manyToOne:
        action:
            targetEntity: ActionEntity
            joinColumn:
                name: action_id
        thenRule:
            targetEntity: RuleEntity
            inversedBy: thenActions
            joinColumn:
                name: then_rule_id
        elseRule:
            targetEntity: RuleEntity
            inversedBy: elseActions
            joinColumn:
                name: else_rule_id
