<?php

namespace Mesd\RuleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ActionCallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActionCallRepository extends EntityRepository
{
}
