<?php

namespace Mesd\RuleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConditionCollectionRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConditionCollectionRepository extends EntityRepository
{
}
