<?php

namespace Mesd\RuleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContextRepository extends EntityRepository
{
    /**
     * Load all
     *
     * @return array All of the contexts saved in the database
     */
    public function loadAll() {
        $qb = $this->createQueryBuilder('context');
        $qb->select('context');
        return $qb->getQuery()->getResult();
    }
}
