<?php

namespace Mesd\RuleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ServiceRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends EntityRepository
{
    /**
     * Load all.
     *
     * @return array All of the services saved in the database
     */
    public function loadAll()
    {
        $qb = $this->createQueryBuilder('service');
        $qb->select('service');

        return $qb->getQuery()->getResult();
    }
}
